name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: echo install dependencies
    - name: Build
      run: echo Execute build
    - name: Run tests
      run: echo test execution
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true        
    - name: Run Azure PowerShell script
      id: GetUrl
      run: |
          $url = (Get-AzLogicAppTriggerCallbackUrl -ResourceGroupName actionsdemo -Name MyFirstLogiApp -TriggerName manual).Value
          echo "::set-output name=LogicAppUrl::$url"
    - name: Print Url
      run: echo ${{ steps.GetUrl.outputs.LogicAppUrl }}
