name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: echo install dependencies
    - name: Build
      run: echo Execute build
    - name: Run tests
      run: echo test execution
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzLogicAppTriggerCallbackUrl -ResourceGroupName vatsamigration -Name test2 -TriggerName manual
        azPSVersion: '3.1.0'
    
